apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kiy6t0tw9-nodejs 
  janus-idp.io/tekton: kiy6t0tw9-nodejs
  backstage.io/kubernetes-id: kiy6t0tw9-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kiy6t0tw9-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml